"""empty message

Revision ID: d728826fe89a
Revises: 
Create Date: 2020-09-05 20:22:19.764927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd728826fe89a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('m_id', sa.Integer(), nullable=False),
    sa.Column('m_title', sa.String(length=255), nullable=True),
    sa.Column('m_img', sa.String(length=200), nullable=True),
    sa.Column('m_url', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('m_id'),
    mysql_charset='utf8mb4'
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_charset='utf8mb4'
    )
    op.create_table('ratings',
    sa.Column('rating_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('m_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['m_id'], ['movies.m_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('rating_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ratings')
    op.drop_table('users')
    op.drop_table('movies')
    # ### end Alembic commands ###
